name: Fetch
on: [push, workflow_dispatch]
jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: {python-version: '3.x'}
    - run: pip install requests beautifulsoup4
    - run: python run.py
    - uses: actions/upload-artifact@v4
      with:
        name: dump
        path: dump
    - if: github.actor != 'github-actions[bot]'
      run: |
        git config user.email action@bot
        git config user.name actionbot
        git add dump2
        git commit -m '[skip ci] dump' || true
        git push
